#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

name: Build and test

on:
  workflow_dispatch:
  push:
    branches: [master, "v*"]
  pull_request:
    branches: [master, "v*"]

jobs:
  format:
    runs-on: ubuntu-latest
    env:
      DEFAULT_FEATURES: "polars,datafusion"

    steps:
      - uses: actions/checkout@v6

      - name: install protoc
        uses: arduino/setup-protoc@v3
        with:
          version: 23.x

      - name: Install minimal stable with clippy and rustfmt
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt,clippy
          cache: true
          # if we ever get rid of all the clippy warnings, we can remove this line
          rustflags: ""

      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1

      - name: Build and Lint with Clippy
        run: cargo clippy --profile=ci --features ${{ env.DEFAULT_FEATURES }} --tests
      
      - name: Run Machete to check for unused dependencies
        uses: bnjbvr/cargo-machete@v0.9.1

  build:
    runs-on: ubuntu-latest
    env:
      DEFAULT_FEATURES: "polars,datafusion"

    steps:
      - uses: actions/checkout@v6

      - name: install protoc
        uses: arduino/setup-protoc@v3
        with:
          version: 23.x

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy
          cache: true
          # if we ever get rid of all the clippy warnings, we can remove this line
          rustflags: ""
     
      - name: build and lint with clippy
        run: cargo clippy --profile=ci --features ${{ env.DEFAULT_FEATURES }}

      - name: Check docs
        run: cargo doc --profile=ci --features ${{ env.DEFAULT_FEATURES }}

      - name: Check no default features (except rustls)
        run: cargo check  --profile=ci --features ${{ env.DEFAULT_FEATURES }}

  integration_test:
    name: integration tests
    runs-on: ubuntu-latest
    env:
      CARGO_INCREMENTAL: 0
      # Disable full debug symbol generation to speed up CI build and keep memory down
      # <https://doc.rust-lang.org/cargo/reference/profiles.html>
      RUSTFLAGS: "-C debuginfo=line-tables-only"
      # https://github.com/rust-lang/cargo/issues/10280
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
      RUST_BACKTRACE: "1"
      DEFAULT_FEATURES: "polars,datafusion"

    steps:
      - uses: actions/checkout@v5

      - name: install protoc
        uses: arduino/setup-protoc@v3
        with:
          version: 23.x

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          cache: true
          # if we ever get rid of all the clippy warnings, we can remove this line
          rustflags: ""
      
      - name: Start emulated services
        run: docker compose up -d

      - name: Run tests
        run: cargo test -p spark-connect-rs --features ${{ env.DEFAULT_FEATURES }}

